// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package proto

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Output_Type int32

const (
	Output_UNBUFFERED Output_Type = 0
	Output_BUFFERED   Output_Type = 1
)

var Output_Type_name = map[int32]string{
	0: "UNBUFFERED",
	1: "BUFFERED",
}
var Output_Type_value = map[string]int32{
	"UNBUFFERED": 0,
	"BUFFERED":   1,
}

func (x Output_Type) String() string {
	return proto.EnumName(Output_Type_name, int32(x))
}
func (Output_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_610d5858699aa088, []int{1, 0}
}

// Input contains client input.
type Input struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Protected            bool     `protobuf:"varint,2,opt,name=protected,proto3" json:"protected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_610d5858699aa088, []int{0}
}
func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (dst *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(dst, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Input) GetProtected() bool {
	if m != nil {
		return m.Protected
	}
	return false
}

// Output contains server output.
type Output struct {
	Data                 string      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Type                 Output_Type `protobuf:"varint,2,opt,name=type,proto3,enum=glas.proto.Output_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_610d5858699aa088, []int{1}
}
func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (dst *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(dst, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Output) GetType() Output_Type {
	if m != nil {
		return m.Type
	}
	return Output_UNBUFFERED
}

func init() {
	proto.RegisterType((*Input)(nil), "glas.proto.Input")
	proto.RegisterType((*Output)(nil), "glas.proto.Output")
	proto.RegisterEnum("glas.proto.Output_Type", Output_Type_name, Output_Type_value)
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_610d5858699aa088) }

var fileDescriptor_api_610d5858699aa088 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xcf, 0x49, 0x2c, 0x86, 0xb0, 0x95, 0x2c, 0xb9,
	0x58, 0x3d, 0xf3, 0x0a, 0x4a, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x19, 0x2e, 0x4e, 0x90, 0xaa, 0xd4, 0xe4, 0x92,
	0xd4, 0x14, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x84, 0x80, 0x52, 0x3e, 0x17, 0x9b, 0x7f,
	0x69, 0x09, 0x2e, 0xbd, 0xda, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x60, 0x6d, 0x7c, 0x46, 0xe2,
	0x7a, 0x08, 0x3b, 0xf5, 0x20, 0xba, 0xf4, 0x42, 0x2a, 0x0b, 0x52, 0x83, 0xc0, 0x8a, 0x94, 0x54,
	0xb8, 0x58, 0x40, 0x3c, 0x21, 0x3e, 0x2e, 0xae, 0x50, 0x3f, 0xa7, 0x50, 0x37, 0x37, 0xd7, 0x20,
	0x57, 0x17, 0x01, 0x06, 0x21, 0x1e, 0x2e, 0x0e, 0x38, 0x8f, 0xd1, 0x89, 0x3d, 0x8a, 0x15, 0x6c,
	0x40, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x6d, 0xd1, 0x20, 0xd4,
	0x00, 0x00, 0x00,
}
